#!/usr/bin/env bash
#Fizz<-3, Buzz<-5, FizzBuzz<-(5,3)

for i in {1..100}; do

  if [[ "$i % 3" -eq 0 ]] && [[ "$i % 5" -eq 0 ]]; then
    echo "FizzBuzz"
  elif [[ "$i % 3" -eq 0 ]]; then
    echo "Fizz"
  elif [[ "$i % 5" -eq 0 ]]; then
    echo "Buzz"
  else
    echo "$i"
  fi
done
