#!/usr/bin/env bash
#SUCH AWK

./102-lets_parse_apache_logs | sort | awk 'BEGIN {SUM=0;IP=""} 
{ if (IP=="") {IP=$1;CODE=$2} }
{ if (IP==$1 && CODE==$2) {(SUM++)}
  else
    {printf ("%s %s %s\n",SUM, IP, CODE);
    IP=$1
    CODE=$2
    SUM=1}
}' | sort -r -n
