#!/usr/bin/env bash
#SUCH AWK

IP=""

./102-lets_parse_apache_logs | sort | awk 'BEGIN {SUM="0"} 
{ if (IP=="") IP=$1 }
{ if (IP==$1) {(++SUM)}
  else
    {print SUM,IP,$2
    IP=$1
    SUM=1}
}' | sort -r -n
