#!/usr/bin/env bash
#Diplay 12 hours

h="0"
m="60"

while true
do
  if [ "$h" -eq 13 ] && [ "$m" -eq 60 ]
  then
    break
  fi

  if [ "$m" -eq 60 ]; then
    echo "Hour: $h"
    ((h++))
    ((m=1))
  fi

  echo "$m"
  ((m++))
done
